@base = http://localhost:4000
@ts = {{$timestamp}}
@email = ada.{{ts}}@example.com

### Login user (adjust email if needed)
# @name login
POST {{base}}/api/v1/mongo/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "secret123"
}

###
@token = {{login.response.body.token}}

### Me: get profile
GET {{base}}/api/v1/mongo/users/me
Authorization: Bearer {{token}}

### Me: update profile
PATCH {{base}}/api/v1/mongo/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstname": "Ada",
  "lastname": "Updated",
  "phone": "0123456789"
}

### Me: change password
PATCH {{base}}/api/v1/mongo/users/me/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "secret123",
  "newPassword": "secret456"
}

### Me: upload profile image
PATCH {{base}}/api/v1/mongo/users/me/image
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="chair.jpg"
Content-Type: image/jpeg

< ./chair.jpg
--WebAppBoundary--
